# filepath: Dockerfile

# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set environment variables
RUN addgroup --system app && adduser --system --group app

# Set the working directory in the container
WORKDIR /app

# Install Poetry
RUN pip install poetry

# Don't create the poetry cache directory in the Dockerfile
# as it will be a volume mount
ENV POETRY_VIRTUALENVS_IN_PROJECT=true
ENV POETRY_CACHE_DIR=/tmp/poetry_cache

# Copy project files
COPY pyproject.toml poetry.lock* ./

# Don't run poetry install here as we'll do it in the compose command
# to ensure we have the mounted volume set up first

# Copy the rest of the application code
COPY . .

# Add an entrypoint script for better initialization
RUN chmod +x test-entrypoint.sh

# IMPORTANT: DO NOT try to remove /tmp/poetry_cache here
# as it will be a mounted volume in docker-compose

# Add entrypoint script

ENTRYPOINT ["./test-entrypoint.sh"]
CMD ["poetry", "run", "pytest"]