"""Initial migration with all tables

Revision ID: xxxxxxxxxxxx # Will be generated by Alembic
Revises:
Create Date: YYYY-MM-DD HH:MM:SS.mmmmmm

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'xxxxxxxxxxxx' # Replace with actual generated ID
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Comentário em português: Cria as extensões necessárias do PostgreSQL.
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp";')
    op.execute('CREATE EXTENSION IF NOT EXISTS "pgcrypto";')
    op.execute('CREATE EXTENSION IF NOT EXISTS "citext";')

    # Comentário em português: Cria a função de trigger para atualizar 'updated_at'.
    op.execute("""
        CREATE OR REPLACE FUNCTION update_updated_at_column()
        RETURNS TRIGGER AS $$
        BEGIN
           NEW.updated_at = timezone('utc', now());
           RETURN NEW;
        END;
        $$ language 'plpgsql';
    """)

    # Comentário em português: Cria a tabela 'users'.
    op.create_table('users',
        sa.Column('user_id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('username', postgresql.CITEXT(), nullable=False),
        sa.Column('email', postgresql.CITEXT(), nullable=False),
        sa.Column('password_hash', sa.Text(), nullable=False),
        sa.Column('full_name', sa.Text(), nullable=True),
        sa.Column('avatar_url', sa.Text(), nullable=True),
        sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
        sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False),
        sa.Column('last_login', sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('user_id', name=op.f('pk_users'))
    )
    # Comentário em português: Cria índices para 'users'.
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # Comentário em português: Aplica o trigger 'updated_at' para 'users'.
    op.execute("""
        CREATE TRIGGER update_users_updated_at BEFORE UPDATE ON users
        FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
    """)

    # Comentário em português: Cria a tabela 'contacts'.
    op.create_table('contacts',
        sa.Column('contact_id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('first_name', sa.Text(), nullable=True),
        sa.Column('last_name', sa.Text(), nullable=True),
        sa.Column('email', postgresql.CITEXT(), nullable=True),
        sa.Column('phone', sa.Text(), nullable=True),
        sa.Column('company', sa.Text(), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_contacts_user_id_users'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('contact_id', name=op.f('pk_contacts')),
        sa.UniqueConstraint('user_id', 'email', name=op.f('uq_contacts_user_id_email'))
    )
    # Comentário em português: Cria índice para 'contacts'.
    op.create_index(op.f('ix_contacts_user_id'), 'contacts', ['user_id'], unique=False)
    # Comentário em português: Aplica o trigger 'updated_at' para 'contacts'.
    op.execute("""
        CREATE TRIGGER update_contacts_updated_at BEFORE UPDATE ON contacts
        FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
    """)

    # Comentário em português: Cria a tabela 'forms'.
    op.create_table('forms',
        sa.Column('form_id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('title', sa.Text(), nullable=False),
        sa.Column('structure', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('form_id', name=op.f('pk_forms'))
    )
    # Comentário em português: Aplica o trigger 'updated_at' para 'forms'.
    op.execute("""
        CREATE TRIGGER update_forms_updated_at BEFORE UPDATE ON forms
        FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
    """)

    # Comentário em português: Cria a tabela 'calendar_events'.
    op.create_table('calendar_events',
        sa.Column('event_id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('title', sa.Text(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('start_time', sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column('end_time', sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column('is_recurring', sa.Boolean(), server_default='false', nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_calendar_events_user_id_users'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('event_id', name=op.f('pk_calendar_events'))
    )
    # Comentário em português: Cria índice para 'calendar_events'.
    op.create_index(op.f('ix_calendar_events_user_id_start_time'), 'calendar_events', ['user_id', 'start_time'], unique=False)
    # Comentário em português: Aplica o trigger 'updated_at' para 'calendar_events'.
    op.execute("""
        CREATE TRIGGER update_calendar_events_updated_at BEFORE UPDATE ON calendar_events
        FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
    """)

    # Comentário em português: Cria a tabela 'messages'.
    op.create_table('messages',
        sa.Column('message_id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('sender_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('receiver_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['receiver_id'], ['users.user_id'], name=op.f('fk_messages_receiver_id_users'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['sender_id'], ['users.user_id'], name=op.f('fk_messages_sender_id_users'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('message_id', name=op.f('pk_messages'))
    )
    # Comentário em português: Cria índice para 'messages'.
    op.create_index(op.f('ix_messages_sender_receiver'), 'messages', ['sender_id', 'receiver_id'], unique=False)

    # Comentário em português: Cria a tabela 'user_photos'.
    op.create_table('user_photos',
        sa.Column('photo_id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('url', sa.Text(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('uploaded_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_user_photos_user_id_users'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('photo_id', name=op.f('pk_user_photos'))
    )
    # Comentário em português: Cria índice para 'user_photos'.
    op.create_index(op.f('ix_user_photos_user_id'), 'user_photos', ['user_id'], unique=False)

    # Comentário em português: Cria a tabela 'form_responses'.
    op.create_table('form_responses',
        sa.Column('response_id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('form_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('source_pdf_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('status', sa.Text(), server_default='pending', nullable=False),
        sa.Column('submitted_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('processed_at', sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['form_id'], ['forms.form_id'], name=op.f('fk_form_responses_form_id_forms'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_form_responses_user_id_users'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('response_id', name=op.f('pk_form_responses'))
    )
    # Comentário em português: Cria índices para 'form_responses'.
    op.create_index(op.f('ix_form_responses_form_id'), 'form_responses', ['form_id'], unique=False)
    op.create_index(op.f('ix_form_responses_user_id'), 'form_responses', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Comentário em português: Remove as tabelas e índices na ordem inversa da criação.
    op.drop_index(op.f('ix_form_responses_user_id'), table_name='form_responses')
    op.drop_index(op.f('ix_form_responses_form_id'), table_name='form_responses')
    op.drop_table('form_responses')
    op.drop_index(op.f('ix_user_photos_user_id'), table_name='user_photos')
    op.drop_table('user_photos')
    op.drop_index(op.f('ix_messages_sender_receiver'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_calendar_events_user_id_start_time'), table_name='calendar_events')
    op.drop_table('calendar_events')
    op.drop_table('forms') # Trigger é removido automaticamente ao dropar a tabela
    op.drop_index(op.f('ix_contacts_user_id'), table_name='contacts')
    op.drop_table('contacts') # Trigger é removido automaticamente
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users') # Trigger é removido automaticamente

    # Comentário em português: Remove a função de trigger.
    op.execute('DROP FUNCTION IF EXISTS update_updated_at_column();')

    # Comentário em português: Opcionalmente, remover extensões (geralmente não é necessário no downgrade).
    # op.execute('DROP EXTENSION IF EXISTS "citext";')
    # op.execute('DROP EXTENSION IF EXISTS "pgcrypto";')
    # op.execute('DROP EXTENSION IF EXISTS "uuid-ossp";')
    # ### end Alembic commands ###

